language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
     secure: QXj/jePnw/kyzpeMunCyyrdyuhBua9Ka+TeLBGSmIUkJY8ifl2cQneHwggRgHU7z5KTI3D87DvE/pHGp5Oame0D0Dg6xvgN8siuuEQrfc9k9t+6IdWpRulh1kafs37n5Azataibt74q0qbbGzvGkSSNtYQe61nJvyED8jpyVsBk9UP6J8mJrM7dqr/6Wlyjce05q6KJcWyQQ3Voum+QGY/GCR7F2GbhjRCSWQ2ct9EG6jbN6NXwGgUGgA31YMsnqpaoFhU9OV4xuKBWw2kA7YNBGmxS0ktctMPof0xzvdBfJXpalAYBRpAHOd5CdZxW4r1B9m/QUh8nH/rmlWBP0KkJ2jULDHsRSVg3JD84ZOEJB7EJOJS1TzO7La7PQvS9tfO7uU/RL3FbXT/P3xM6hbBDZrp8rvYZacMc6XlBfMJKyCXCwBvQ7JaqCdAR47Agib1orGVT4VQgrn6PYTtoQxsdp4VTdGfbaf7Un7Pm8OU/jxnYsRn3t+4r+jhWkNnzV88eFMjQQlU5ix5sZowguFeZwwfIbpDZHRx8swydSS9hEVLSnC8xgA1tl+RsxWxa9LFlaIKmsRL1SXEtLN4r3FTCurXv4adXYiWpPgf+hm8u/oSkMN/wVsj4WnpeOfU1WbQEM0QvvPBiaLWKhovpPbIdLGiZlpYywwwjW0DmuYoU=
  on:
    branch: master
